"""Initialize default data"""
import uuid
from datetime import datetime
from app.domain.entities.user import User, UserRole
from app.infrastructure.config.settings import settings


async def init_default_admin():
    """Initialize default admin user if it doesn't exist"""
    from app.infrastructure.database.base import SessionLocal
    from app.infrastructure.repositories.user_repository_db import UserRepositoryDB
    
    db = SessionLocal()
    try:
        repository = UserRepositoryDB(db)
        
        # Check if admin already exists
        admin_username = settings.DEFAULT_ADMIN_USERNAME
        existing_admin = await repository.get_by_username(admin_username)
        
        if existing_admin:
            print(f"✅ Default admin user '{admin_username}' already exists")
            # Verify password works
            password_works = await repository.verify_password(admin_username, settings.DEFAULT_ADMIN_PASSWORD)
            if not password_works:
                print(f"⚠️  Admin password doesn't work, resetting password...")
                # Delete existing admin
                await repository.delete(existing_admin.id)
                print(f"   Deleted existing admin, will recreate...")
            else:
                print(f"   Password verification: OK")
                return
        
        # Create default admin directly (bypassing use cases validation for first admin)
        try:
            # Validate email domain
            if not settings.DEFAULT_ADMIN_EMAIL.lower().endswith('@kostalegal.com'):
                print(f"❌ Invalid admin email domain: {settings.DEFAULT_ADMIN_EMAIL}")
                return
            
            # Check if email already exists
            all_users = await repository.get_all()
            if any(u.email.lower() == settings.DEFAULT_ADMIN_EMAIL.lower() for u in all_users):
                print(f"❌ User with email '{settings.DEFAULT_ADMIN_EMAIL}' already exists")
                return
            
            # Create admin user directly (id will be generated by repository.create)
            admin_user = User(
                id="",  # Will be generated by repository
                username=admin_username,
                email=settings.DEFAULT_ADMIN_EMAIL,
                role=UserRole.ADMIN,
                blocked=False,
            )
            
            # Create user with password
            print(f"[DEBUG] Creating admin with password: '{settings.DEFAULT_ADMIN_PASSWORD}'")
            created_admin = await repository.create(admin_user, settings.DEFAULT_ADMIN_PASSWORD)
            
            # Verify admin was created and password works
            verify_admin = await repository.get_by_username(admin_username)
            if verify_admin:
                print(f"   Admin ID: {verify_admin.id}")
                print(f"   Admin role: {verify_admin.role.value}")
                # Test password verification immediately
                print(f"[DEBUG] Testing password verification immediately after creation...")
                password_check = await repository.verify_password(admin_username, settings.DEFAULT_ADMIN_PASSWORD)
                if not password_check:
                    print(f"   ❌ Password verification FAILED immediately after creation!")
                    print(f"   This indicates a problem with password hashing/verification")
                    return
                print(f"   ✅ Password verification test: PASSED")
            
            print(f"✅ Default admin user created successfully!")
            print(f"   Username: {settings.DEFAULT_ADMIN_USERNAME}")
            print(f"   Email: {settings.DEFAULT_ADMIN_EMAIL}")
            print(f"   Password: {settings.DEFAULT_ADMIN_PASSWORD}")
            print(f"   ⚠️  Please change the default password after first login!")
        except Exception as e:
            print(f"❌ Failed to create default admin: {e}")
            import traceback
            traceback.print_exc()
            db.rollback()
    finally:
        db.close()



